"""Create a portable JAV copy on a removable drive or another folder.

Usage:
    python scripts/install_portable.py E:/JAV
    python scripts/install_portable.py /media/user/USB/JAV

It copies the project, creates data/brain, data/workspace and data/screenshots,
and writes .env so memory/workspace stay inside that portable folder.
"""
from __future__ import annotations

import argparse
import shutil
from pathlib import Path

EXCLUDE_DIRS = {"__pycache__", ".git", ".venv", "venv", "dist", "build"}
EXCLUDE_SUFFIXES = {".pyc", ".pyo", ".log"}


def should_ignore(path: Path) -> bool:
    if path.name in EXCLUDE_DIRS:
        return True
    if path.suffix.lower() in EXCLUDE_SUFFIXES:
        return True
    return False


def copy_tree(src: Path, dst: Path) -> None:
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        if should_ignore(item):
            continue
        target = dst / item.name
        if item.is_dir():
            copy_tree(item, target)
        else:
            shutil.copy2(item, target)


def upsert_env(env_path: Path, updates: dict[str, str]) -> None:
    lines = env_path.read_text(encoding="utf-8", errors="ignore").splitlines() if env_path.exists() else []
    out: list[str] = []
    seen: set[str] = set()
    for line in lines:
        if "=" in line and not line.lstrip().startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in updates:
                out.append(f"{key}={updates[key]}")
                seen.add(key)
            else:
                out.append(line)
        else:
            out.append(line)
    if out and out[-1].strip():
        out.append("")
    out.append("# Portable mode generated by scripts/install_portable.py")
    for key, value in updates.items():
        if key not in seen:
            out.append(f"{key}={value}")
    env_path.write_text("\n".join(out).rstrip() + "\n", encoding="utf-8")


def write_launchers(dst: Path) -> None:
    (dst / "run_desktop_portable.bat").write_text(
        "@echo off\r\n"
        "cd /d %~dp0\r\n"
        "python main.py --desktop\r\n"
        "pause\r\n",
        encoding="utf-8",
    )
    sh = dst / "run_desktop_portable.sh"
    sh.write_text("#!/usr/bin/env bash\ncd \"$(dirname \"$0\")\"\npython3 main.py --desktop\n", encoding="utf-8")
    try:
        sh.chmod(0o755)
    except Exception:
        pass


def main() -> None:
    parser = argparse.ArgumentParser(description="Install JAV as a portable folder")
    parser.add_argument("target", help="Target folder, e.g. E:/JAV or /media/user/USB/JAV")
    args = parser.parse_args()

    src = Path(__file__).resolve().parents[1]
    dst = Path(args.target).expanduser().resolve()
    if src == dst or src in dst.parents:
        raise SystemExit("Choose a target outside the current project folder.")

    copy_tree(src, dst)
    brain = dst / "data" / "brain"
    workspace = dst / "data" / "workspace"
    screenshots = dst / "data" / "screenshots"
    for folder in (brain, workspace, screenshots):
        folder.mkdir(parents=True, exist_ok=True)

    env_src = dst / ".env"
    if not env_src.exists() and (dst / ".env.example").exists():
        shutil.copy2(dst / ".env.example", env_src)

    upsert_env(env_src, {
        "JAV_PORTABLE": "true",
        "JARVIS_DATA_DIR": "data/brain",
        "ACTION_WORKSPACE_PATH": "data/workspace",
        "SCREENSHOT_DIR": "data/screenshots",
        "MEMORY_SQLITE_ENABLED": "true",
        "MEMORY_VECTOR_ENABLED": "true",
        "MEMORY_VECTOR_DIMENSIONS": "256",
        "MEMORY_EPISODIC_RETENTION_DAYS": "3650",
        "MEMORY_EPISODIC_MAX_ITEMS": "100000",
        "MEMORY_SEARCH_TOP_K": "8",
        "WEB_LEARNING_ENABLED": "true",
        "WEB_SEARCH_ENABLED": "true",
        "WEB_LEARN_STORE_ENABLED": "true",
        "WEB_SEARCH_MAX_RESULTS": "5",
        "WEB_LEARN_MAX_SOURCES": "4",
    })
    write_launchers(dst)
    print(f"Portable JAV installed to: {dst}")
    print(f"Memory: {brain}")
    print(f"Workspace: {workspace}")
    print(f"Screenshots: {screenshots}")
    print(".env uses relative paths, so the portable drive can change drive letter/mount point.")


if __name__ == "__main__":
    main()
